### ISSUE TITLE
Web(chrome) get a error : Unsupported operation: Platform._operatingSystem 

### ISSUE THREAD

**Issue by yunbai002** [casdoor/casdoor-flutter-example#13]
Web(chrome) get a error : Unsupported operation: Platform._operatingSystem

**Comment by hsluoyz** [comment]
@yunbai002 can you post a small video here to show the error? Like here: https://github.com/casdoor/casdoor-flutter-example?tab=readme-ov-file#after-running-you-will-see-the-following--interfaces

![image](https://github.com/casdoor/casdoor-flutter-example/assets/3787410/9f2e5a49-b20e-4d3a-b97b-c23b73a7d2b5)

**Comment by yunbai002** [comment]
It's ease to replicate. This is the steps:
1  Get the demo:  git clone https://github.com/casdoor/casdoor-flutter-example.git
2  cd ./casdoor-flutter-example   && flutter pub get
3  Use VSCode open the project, and set the "AuthConfig"
4  Run the cmd : flutter run -d chrome,     then you will get this error in the new brower window. 

It's ok at the platform of windows.

**Comment by yunbai002** [comment]
My flutter version is 3.16.4

**Comment by yunbai002** [comment]
![casdoore](https://github.com/casdoor/casdoor-flutter-example/assets/127473188/3e88ae6e-82f9-4b79-804e-16a48ddbe172)
@hsluoyz   Like this

**Comment by hsluoyz** [comment]
@yunbai002 I can't reproduce this issus under:

- Flutter:

```
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (6 months ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
```

Browser:

UA: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`

![image](https://github.com/casdoor/casdoor-flutter-example/assets/3787410/8c42ef3a-f935-4092-9487-9b02217ef34a)


Maybe you can try something like: https://github.com/miguelpruivo/flutter_file_picker/issues/1131#issuecomment-1445451372

**Comment by Mcayear** [comment]
`flutter clean` cannot solve this problem because you are pulling dependencies for the first time after `git clone`.

The reason for this error is that `dart:io` does not support web. The solution is to use conditional imports.

## main.dart
```dart
import 'dart:convert';
import 'dart:io' if (dart.library.html) './web_platform_adapter.dart';
```

## web_platform_adapter.dart
```dart
class Platform {
  static bool get isWeb => true;
  static bool get isMacOS => false;
  static bool get isLinux => false;
  static bool get isWindows => false;
}
```
