### ISSUE TITLE
some questions about casbin flutter sdk

### ISSUE THREAD

**Issue by nexa-li** [casdoor/casdoor-flutter-example#2]
Can Casdoor flutter sdk realize not to jump to the web page authorization, but directly use the ui on the flutter side to implement related interaction logic with the backend

**Comment by hsluoyz** [comment]
@JarynChen plz edit your issue title and content to change to English

![image](https://user-images.githubusercontent.com/3787410/180590610-f14ebaf2-d126-4030-b793-3054b73c6d34.png)

**Comment by hsluoyz** [comment]
@ziliangyu 

/cc @xiaobeiswift

**Comment by ziliangyu** [comment]
@JarynChen 
You mean to write an interface with flutter that is the same as the front end of casdoor?like this?
![0R2 5 S51LIQXJSVD9TFQ3I](https://user-images.githubusercontent.com/53009950/180603300-82e61881-6b25-44f4-b58c-1592bd9dd8f5.png)

**Comment by nexa-li** [comment]
> @JarynChen You mean to write an interface with flutter that is the same as the front end of casdoor?like this? ![0R2 5 S51LIQXJSVD9TFQ3I](https://user-images.githubusercontent.com/53009950/180603300-82e61881-6b25-44f4-b58c-1592bd9dd8f5.png)

Yes，but not just the ui, I also want to know the interactive method. Because I think many flutter apps prefer complete the login operation in the app inside.

**Comment by hsluoyz** [comment]
@JarynChen the Casdoor login page (web frontend) has very complicated logic at: https://github.com/casdoor/casdoor/blob/master/web/src/auth/LoginPage.js , it would be nearly impossible for you to create a Flutter native one for it. You are welcome to try it but what I suggest is keeping using the webview way which has Casdoor web login page embedded.

**Comment by nexa-li** [comment]
> @JarynChen the Casdoor login page (web frontend) has very complicated logic at: https://github.com/casdoor/casdoor/blob/master/web/src/auth/LoginPage.js , it would be nearly impossible for you to create a Flutter native one for it. You are welcome to try it but what I suggest is keeping using the webview way which has Casdoor web login page embedded.

Thanks.
