### ISSUE TITLE
Failed Login 

### ISSUE THREAD

**Issue by hadievm** [casdoor/casdoor-flutter-example#6]
I tried to run and login, but its failed to authentication..
this link is open when click floating login button

https://door.casdoor.com/login/oauth/authorize?client_id=014ae4bd048734ca2dea&response_type=code&scope=read&state=app-casnode&code_challenge_method=S256&code_challenge=gGeR4msY63XrB_7OTUDdqbspLLIk0ddn70RuCIhLrbI&redirect_uri=casdoor%3A%2F%2Fcallback

use default login 
username : admin
pass : 123

**Comment by hsluoyz** [comment]
@maquejp @ziliangyu

**Comment by hsluoyz** [comment]
@hadievm now the password has been restored, you can try again
