### ISSUE TITLE
Get Error: XMLHttpRequest error on clean example

### ISSUE THREAD

**Issue by pyxiscloud** [casdoor/casdoor-flutter-example#7]
1. Git clone this repo
2. Run on 9000 port and login admin 123 
3. Got "Error: XMLHttpRequest error."
![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/9dfee4af-7017-40d2-b125-58182f6215b5)

**Comment by pyxiscloud** [comment]
Looks like we need some settings to accept CORS on the Casdoor server

**Comment by hsluoyz** [comment]
@pyxiscloud do you run this example in PC web browser? There will be a CORS cross-site issue when your `casdoor-flutter-example` frontend code calls into Casdoor backend (which is in a different domain).

Casdoor uses the application's Redirect URIs field to allow specific CORS origins to access its API:

https://github.com/casdoor/casdoor/blob/666ff48837016de9c47434dec1aeb8ddbe509fc9/routers/cors_filter.go#L32-L40

Add your `localhost:9000` to: https://door.casdoor.com/applications/casbin/app-example

![image](https://github.com/casdoor/casdoor-flutter-example/assets/3787410/466e866e-a918-4f1b-9e04-643ba4c8ef91)

**Comment by hsluoyz** [comment]
@Wrapping-2000 add the docs

**Comment by pyxiscloud** [comment]
Sorry, but this example still not working,
Tried at localhost: 9000,  localhost: 5000, localhost: 5001

Thought this repo should work out of the box?

**Comment by cwp0** [comment]
@pyxiscloud 
I run it successfully locally, please follow the steps below:
1. Please refer to https://github.com/casdoor/casdoor-flutter-sdk/pull/25/files，add parsePort()
2. Deploy casdoor locally, and create an application, add a redirection URL to http://localhost:9000/callback.html
<img width="1415" alt="截屏2023-07-13 11 21 27" src="https://github.com/casdoor/casdoor-flutter-example/assets/110087455/3b3972e2-ad2a-45aa-aa67-54c873c3486d">


3. your casdoor config just like this:

**Comment by cwp0** [comment]
<img width="435" alt="截屏2023-07-13 11 27 49" src="https://github.com/casdoor/casdoor-flutter-example/assets/110087455/37f08a8f-ad18-410c-9865-776d58147892">

**Comment by hsluoyz** [comment]
@pyxiscloud plz use latest master branch code, it should have been fixed

**Comment by pyxiscloud** [comment]
In your example settings you use "localhost" as casdoor server and run flutter frontend on localhost too.
Thats why you don't get the  "Error: XMLHttpRequest error."

I've tried this with your public casdoor server and got  "Error: XMLHttpRequest error." This is latest version.

![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/8a38f2ad-19d8-49db-ab59-cd4be7c9e338)


Please try to run on public domain (serverUrl) and flutter on localhost

**Comment by hsluoyz** [comment]
@pyxiscloud it's a CORS issue. Here's how to fix:

1. Pull this repo's code to latests
2. Use latest Casdoor code, must contain this commit: https://github.com/casdoor/casdoor/commit/bd06996bab5bd467854503d65ba3ac9c0232e1f4

**Comment by pyxiscloud** [comment]
I use docker, does it contains in https://hub.docker.com/layers/casbin/casdoor/v1.363.0/images/sha256-c98cf45f8b5309b3af3ad1eae604460513e40272cfb07fa654206da23bc3d88c?context=explore?

**Comment by hsluoyz** [comment]
@pyxiscloud Use v1.364.0: https://github.com/casdoor/casdoor/releases/tag/v1.364.0

**Comment by pyxiscloud** [comment]
now works fine, thank you

**Comment by pyxiscloud** [comment]
Now it has same CORS trouble with "api/login/oauth/logout"

![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/9ee8ad68-dde9-4d47-84b4-507747b322cd)
How can I fix it?

**Comment by hsluoyz** [comment]
@pyxiscloud are there any other APIs, so can add them all?

**Comment by pyxiscloud** [comment]
@hsluoyz 
yes, please:
- all Session API
![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/326b96cc-ee8e-4a27-984d-59821a2c7cc2)

- all Token API
![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/e380a178-dd15-4703-b11d-b9655d252595)

- all User API
![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/17de7f6b-b8a2-4151-9d01-d4208189b151)

- all Login API
![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/3c3c9844-6cb2-491d-88a6-921daae90fcd)


thank you!

**Comment by hsluoyz** [comment]
@pyxiscloud those APIs should not be exposed by CORS to frontend. It's big security hole.

**Comment by pyxiscloud** [comment]
@hsluoyz , 
/api/logout - can you add this please?

**Comment by hsluoyz** [comment]
@pyxiscloud "api/login/oauth/logout" or "/api/logout"?

**Comment by pyxiscloud** [comment]
I need API to logout from Flutter Web application
At swagger doc there is only this method:
![image](https://github.com/casdoor/casdoor-flutter-example/assets/14041313/96063222-939f-4686-aa0f-d3423fa508d8)

Should I use "api/login/oauth/logout"?

**Comment by hsluoyz** [comment]
@pyxiscloud you should just logout inside Flutter, no need to logout Casdoor. See latest example code: https://github.com/casdoor/casdoor-flutter-example/commit/5b8e39d78884942429af06d9eb7575fc5d5e7d3f

**Comment by pyxiscloud** [comment]
Please check this case:
1. run flutter and login to app (**auto sign in enabled**)
2. logout from flutter app (delete token from storages and memory)
3. go to "Forgot password" and change password (https://DOMAIN/forget/APPNAME)
4. now I open app and after click login it auto login without any password asking. But it should ask login and password, just beacause it maybe another user

think it open new page with casdoor login, then auto login with credentials that stores on casdoor tab (flutter app can't remove saved settings on casdoor tab)

**Comment by hsluoyz** [comment]
@pyxiscloud if you have enabled `Auto Sign` in the application of Casdoor, Casdoor will remember your session via cookie. The session doesn't destroy automatically after you changed the password.

You can either disable `Auto Sign` or manually kick that user off in Sessions page: https://door.casdoor.com/sessions . If you have more questions, plz send GitHub issue to Casdoor's repo, as it has nothing to do with casdoor-flutter-example
